require_relative('../models/product')
require_relative('../models/manufacturer')

Product.delete_all
Manufacturer.delete_all

manufacturer1 = Manufacturer.new({ 'name' => 'scubapro', 'country' => 'usa', 'contact' => 'jeff', 'phone' => '001 601 5647', 'notes' => 'September discount 10%', 'rating' => 5 })
manufacturer1.save()

manufacturer2 = Manufacturer.new({ 'name' => 'mares', 'country' => 'italy', 'contact' => 'lucio', 'phone' => '0039 986475', 'notes' => 'October discount 10% on spend over £1000', 'rating' => 4 })
manufacturer3 = Manufacturer.new({ 'name' => 'suunto', 'country' => 'finland', 'contact' => 'elena', 'phone' => '358 6573849', 'notes' => '', 'rating' => 5 })
manufacturer4 = Manufacturer.new({ 'name' => 'apeks', 'country' => 'uk', 'contact' => 'elke', 'phone' => '0161 2452438', 'notes' => '', 'rating' => 4 })

manufacturer2.save()
manufacturer3.save()
manufacturer4.save()

#
product1 = Product.new({ 'name' => 'mk25', 'description' => 'regulator', 'quantity' => 5, 'buy_cost' => 580.95, 'sell_price' => 675, 'image' => 'mk25.jpg', 'manufacturer_id' => manufacturer1.id })
product2 = Product.new({ 'name' => 'xforce', 'description' => 'bcd', 'quantity' => 8, 'buy_cost' => 395.80, 'sell_price' => 450, 'image' => 'xforce.jpg', 'manufacturer_id' => manufacturer1.id })
product3 = Product.new({ 'name' => 'apnea', 'description' => 'wetsuit', 'quantity' => 2, 'buy_cost' => 120.50, 'sell_price' => 180, 'image' => 'apnea.jpg', 'manufacturer_id' => manufacturer2.id })
product4 = Product.new({ 'name' => 'avanti', 'description' => 'fins', 'quantity' => 1, 'buy_cost' => 70, 'sell_price' => 85, 'image' => 'avanti.jpg', 'manufacturer_id' => manufacturer2.id })
product5 = Product.new({ 'name' => 'vyper', 'description' => 'computer', 'quantity' => 3, 'buy_cost' => 290, 'sell_price' => 320, 'image' => 'vyper.jpg', 'manufacturer_id' => manufacturer3.id })
product6 = Product.new({ 'name' => 'd4', 'description' => 'computer', 'quantity' => 2, 'buy_cost' => 230, 'sell_price' => 265, 'image' => 'd4.jpg', 'manufacturer_id' => manufacturer3.id })
product7 = Product.new({ 'name' => 'xtx', 'description' => 'regulator', 'quantity' => 4, 'buy_cost' => 390, 'sell_price' => 450, 'image' => 'xtx.jpg', 'manufacturer_id' => manufacturer4.id })
product8 = Product.new({ 'name' => 'rk3', 'description' => 'fins', 'quantity' => 2, 'buy_cost' => 70, 'sell_price' => 99.99, 'image' => 'rk3.jpg', 'manufacturer_id' => manufacturer4.id })
product9 = Product.new({ 'name' => '12l dumpy', 'description' => 'cylinder', 'quantity' => 5, 'buy_cost' => 105, 'sell_price' => 149.99, 'image' => 'cylinder.jpg', 'manufacturer_id' => manufacturer1.id })
product10 = Product.new({ 'name' => 'ergo', 'description' => 'snorkel', 'quantity' => 8, 'buy_cost' => 25, 'sell_price' => 49.99, 'image' => 'ergo.jpg', 'manufacturer_id' => manufacturer2.id })
product11 = Product.new({ 'name' => 'everflex', 'description' => 'hood', 'quantity' => 7, 'buy_cost' => 55, 'sell_price' => 79.99, 'image' => 'evrflex.jpg', 'manufacturer_id' => manufacturer1.id })
product12 = Product.new({ 'name' => 'flexa', 'description' => 'gloves', 'quantity' => 2, 'buy_cost' => 19.99, 'sell_price' => 59.99, 'image' => 'flexa.jpg', 'manufacturer_id' => manufacturer2.id })
product13 = Product.new({ 'name' => 'novascotia', 'description' => 'drysuit', 'quantity' => 6, 'buy_cost' => 109, 'sell_price' => 189.99, 'image' => 'novascotia.jpg', 'manufacturer_id' => manufacturer1.id })
product14 = Product.new({ 'name' => 'spectra', 'description' => 'snorkel', 'quantity' => 2, 'buy_cost' => 30, 'sell_price' => 49.99, 'image' => 'spectra.jpg', 'manufacturer_id' => manufacturer1.id })
product15 = Product.new({ 'name' => 'tech', 'description' => 'hood', 'quantity' => 2, 'buy_cost' => 30, 'sell_price' => 69.99, 'image' => 'tech.jpg', 'manufacturer_id' => manufacturer1.id })
product16 = Product.new({ 'name' => 'tropic', 'description' => 'gloves', 'quantity' => 10, 'buy_cost' => 35, 'sell_price' => 79.99, 'image' => 'tropic.jpg', 'manufacturer_id' => manufacturer1.id })
product17 = Product.new({ 'name' => 'wahoo', 'description' => 'mask', 'quantity' => 3, 'buy_cost' => 30, 'sell_price' => 49.99, 'image' => 'wahoo.jpg', 'manufacturer_id' => manufacturer4.id })
product18 = Product.new({ 'name' => 'xvision', 'description' => 'mask', 'quantity' => 2, 'buy_cost' => 30, 'sell_price' => 49.99, 'image' => 'xvision.jpg', 'manufacturer_id' => manufacturer4.id })

product1.save()
product2.save()
product3.save()
product4.save()
product5.save()
product6.save()
product7.save()
product8.save()
product9.save()
product10.save()
product11.save()
product12.save()
product13.save()
product14.save()
product15.save()
product16.save()
product17.save()
product18.save()
